export const keyboard = [
   "Backquote",
   "Digit1",
   "Digit2",
   "Digit3",
   "Digit4",
   "Digit5",
   "Digit6",
   "Digit7",
   "Digit8",
   "Digit9",
   "Digit0",
   "Minus",
   "Equal",
   "Backspace",
   "Tab",
   "KeyQ",
   "KeyW",
   "KeyE",
   "KeyR",
   "KeyT",
   "KeyY",
   "KeyU",
   "KeyI",
   "KeyO",
   "KeyP",
   "BracketLeft",
   "BracketRight",
   "Backslash",
   "Delete",
   "CapsLock",
   "KeyA",
   "KeyS",
   "KeyD",
   "KeyF",
   "KeyG",
   "KeyH",
   "KeyJ",
   "KeyK",
   "KeyL",
   "Semicolon",
   "Quote",
   "Enter",
   "ShiftLeft",
   "KeyZ",
   "KeyX",
   "KeyC",
   "KeyV",
   "KeyB",
   "KeyN",
   "KeyM",
   "Comma",
   "Period",
   "Slash",
   "ArrowUp",
   "ShiftRight",
   "ControlLeft",
   "MetaLeft",
   "AltLeft",
   "Space",
   "AltRight",
   "ControlRight",
   "ArrowLeft",
   "ArrowDown",
   "ArrowRight"
   ];

export const dictionary = {
   Backquote: { eng: "`", ru: "ё", shift: "~"},
   Digit1: { eng: "1", ru: "1", shift: "!"},
   Digit2: { eng: "2", ru: "2", shift: "@"},
   Digit3: { eng: "3", ru: "3", shift: "#"},
   Digit4: { eng: "4", ru: "4", shift: "$"},
   Digit5: { eng: "5", ru: "5", shift: "%"},
   Digit6: { eng: "6", ru: "6", shift: "^"},
   Digit7: { eng: "7", ru: "7", shift: "&"},
   Digit8: { eng: "8", ru: "8", shift: "*"},
   Digit9: { eng: "9", ru: "9", shift: "("},
   Digit0: { eng: "0", ru: "0", shift: ")"},
   Minus: { eng: "-", ru: "-", shift: "_"},
   Equal: { eng: "=", ru: "=", shift: "+"},
   Backspace: { eng: "←", ru: "←" },

   Tab: { eng: "Tab", ru: "Tab" },
   KeyQ: { eng: "q", ru: "й" },
   KeyW: { eng: "w", ru: "ц" },
   KeyE: { eng: "e", ru: "у" },
   KeyR: { eng: "r", ru: "к" },
   KeyT: { eng: "t", ru: "е" },
   KeyY: { eng: "y", ru: "н" },
   KeyU: { eng: "u", ru: "г" },
   KeyI: { eng: "i", ru: "ш" },
   KeyO: { eng: "o", ru: "щ" },
   KeyP: { eng: "p", ru: "з" },
   BracketLeft: { eng: "[", ru: "х", shift: "{"},
   BracketRight: { eng: "]", ru: "ъ", shift: "}"},
   Backslash: {eng: "\\", ru: "\\", shift: "|"},
   Delete: { eng: "Del", ru: "Del" },

   CapsLock: { eng: "CapsLook", ru: "CapsLook" },
   KeyA: { eng: "a", ru: "ф" },
   KeyS: { eng: "s", ru: "ы" },
   KeyD: { eng: "d", ru: "в" },
   KeyF: { eng: "f", ru: "а" },
   KeyG: { eng: "g", ru: "п" },
   KeyH: { eng: "h", ru: "р" },
   KeyJ: { eng: "j", ru: "о" },
   KeyK: { eng: "k", ru: "л" },
   KeyL: { eng: "l", ru: "д" },
   Semicolon: { eng: ";", ru: "ж", shift: ":"},
   Quote: { eng: "'", ru: "э", shift: "\""},
   Enter: { eng: "Enter", ru: "Enter" },

   ShiftLeft: { eng: "LShift", ru: "LShift" },
   KeyZ: { eng: "z", ru: "я" },
   KeyX: { eng: "x", ru: "ч" },
   KeyC: { eng: "c", ru: "с" },
   KeyV: { eng: "v", ru: "м" },
   KeyB: { eng: "b", ru: "и" },
   KeyN: { eng: "n", ru: "т" },
   KeyM: { eng: "m", ru: "ь" },
   Comma: { eng: ",", ru: "б", shift: "<"},
   Period: { eng: ".", ru: ".", shift: ">"},
   Slash: { eng: "/", ru: ".", shift: "?"},
   ArrowUp: { eng: "↑", ru: "↑" },
   ShiftRight: { eng: "RShift", ru: "Rshift" },

   ControlLeft: { eng: "CTRL", ru: "CTRL" },
   MetaLeft: { eng: "Win", ru: "Win" },
   AltLeft: { eng: "Alt", ru: "Alt" },
   Space: { eng: "_____", ru: "_____" },
   AltRight: { eng: "Alt", ru: "Alt" },
   ArrowLeft: { eng: "←", ru: "←" },
   ArrowDown: { eng: "↓", ru: "↓" },
   ArrowRight: { eng: "→", ru: "→" },
   ControlRight: { eng: "CTRL", ru: "CTRL" },
   };

export const spec_keys = [
      "Backquote",
      "Backspace",
      "Tab",
      "Delete",
      "CapsLock",
      "Enter",
      "ShiftLeft",
      "ShiftRight",
      "ControlLeft",
      "MetaLeft",
      "AltLeft",
      "Space",
      "AltRight",
      "ControlRight",
      ];

export const arrow__keys = ["ArrowLeft", "ArrowDown", "ArrowRight", "ArrowUp"];